#! /bin/sh
sxhkd &
"$HOME"/.config/polybar/launch.sh &
bspc monitor -d term web chat code music 6 7

bspc config border_width         0
bspc config window_gap           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop ^2 -l monocle

bspc rule -a firefox-nightly desktop=^2
bspc rule -a Nightly desktop=^2
bspc rule -a discord desktop=^3
bspc rule -a mplayer2 state=floating
bspc rule -a Gedit state=floating
bspc rule -a pcmanfm state=floating

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
#bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

xsetroot -cursor_name left_ptr
feh --randomize --bg-fill ~/Pictures/wallpapers
mpd&
compton -f &
xrdb -merge ~/.Xdefaults &
redshift &
termite &
firefox-nightly &
discord &
