#! /bin/sh
sxhkd &

bspc config border_width        0
bspc config window_gap          20
bspc config top_padding         0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer       true
bspc config history_aware_focus true

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner

bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9 0

bspc desktop --focus ^1

bspc rule -a Firefox desktop=^2
bspc rule -a chromium-browser desktop=^2
bspc rule -a discord desktop=^3
bspc rule -a mplayer2 state=floating
bspc rule -a Gedit state=floating
bspc rule -a pcmanfm state=floating
bspc rule -a URxvt state=floating
bspc rule -a retroarch state=floating

xsetroot -cursor_name left_ptr &
feh --randomize --bg-fill ~/Pictures/wallpapers &
#mpd &
#compton -f &
xrdb -merge ~/.Xdefaults &
#redshift &
urxvt &
#discord-ptb &
#dunst -conf .config/dunst/dunstrc *
#chromium-browser
Firefox
